params:
  # Data Config
  model: 'DAGRU.yaml'   # 如果你在 model_dict 里注册的名字不是这个，就改成你的实际名字
  task: 'soft_sensor'
  data_name: 'PPGAS'
  data_path: './data/PPGAS/gt_2011.csv'
  target: 'NOX'
  data_aug: False
  use_amp: False
  num_workers: 1
  if_missing: False
  missing_rate: 0
  

  # Model Config
  enc_in: 9
  dec_in: 9
  C_in: 9
  C_out: 1
  seq_len: 16
  label_len: 16
  pred_len: 1

  embed: 'TimeF'
  freq: 's'
  factor: 1
  n_components: 5
  d_model: 64
  n_heads: 4
  e_layers: 1
  d_layers: 1
  d_ff: 128
  dropout: 0.05
  activation: 'gelu'

  # Train Config
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.0
  epoch: 300
  
  patience: 10
  lradj: 'cosine'
  use_tensorboard: False

  # Test Config
  inverse: True

  # GPU Config
  use_cuda: True
  device: 'cuda'
  gpu: 0
  seed: 2021
  device_ids: [0]
  use_multi_gpu: False