
                        python -u run.py \
                        --model 'SparseTSF' \
                        --task 'short_term_forecasting' \
                        --data_name "SRU" \
                        --data_path './data/SRU/SRU_data.csv' \
                        --target 'SO2' \
                        --num_workers 1 \
                        --missing_rate 0 \
                        --enc_in 6 \
                        --C_in 6 \
                        --C_out 1 \
                        --seq_len 16 \
                        --label_len 16 \
                        --pred_len 6 \
                        --period_len 2 \
                        --d_model 64 \
                        --model_type 'mlp' \
                        --batch_size 64 \
                        --learning_rate 0.001 \
                        --epoch 300 \
                        --if_valid False \
                        --patience 10 \
                        --lradj 'cosine' \
                        --inverse \
                        --use_cuda  \
                        --device "cuda" \
                        --gpu 0 \
                        --seed 2021 \
