# configs.yaml

params:
# Data Config
  model: 'Fredformer'
  task: 'soft_sensor' # type: str, default: short_term_forecasting, help: ['short_term_forecasting', 'soft_sensor']
  data_name: "MFP" # type: str, default: None, help: ['MFP', 'DEB', 'SRU','PPGAS','PTA']
  data_path: 'C:\Study\Code\datasets\MFP\data\MFP_combined_data.csv' # type: str, default: None, help: Path to the dataset
  target: 'PT501' # type: str, default: None, help: Target variable name
  data_aug: False # type: bool, default: False, help: If use data augmentation for Deb and SRU dataset Augmentation Options #
  use_amp: False # type: bool, default: False, help: If use automatic mixed precision training
  num_workers: 1 # type: int, DataLoader the number of workers
  if_missing: False # type: bool, default: False, help: If exists Missing Data
  missing_rate: 0 # type: float, default: 0, help: Missing data rate [0:0.5]
  use_axliary_var: False # type: bool, default: False, help: If use mode variable for multi_mode dataset

# Model Config
  enc_in: 16  # Dimension of encoder Input
  dec_in: 16  # Dimension of decoder Input
  C_in: 16  # Dimension of Channel Input
  C_out: 1  # Dimension of Channel Output
  seq_len: 24 #
  patch_len: 8
  stride: 1
  embed: 'TimeF'
  freq: 's'
  factor: 1
  label_len: 16
  pred_len: 1 # Prediction Length,
  d_model: 16
  pd_model: 32 # patch embedding dimension after encoder
  n_heads: 8
  e_layers: 1
  d_layers: 1
  d_ff: 32
  dropout: 0.05
  activation: 'gelu'
  kernel_size: 4 # kernel size for the convolutional layer for envelope detection
  individual: True


# Train Config
  batch_size: 64 #128
  learning_rate: 0.001 # 0.0005
  epoch: 300
  if_valid: True
  patience: 10 # 25
  lradj: 'cosine' # learning rate adjustment strategy: [type1, type2, cosine]
  use_tensorboard: False

# Test Config
  inverse: True # If the data is scaled, inverse the data to the original scale

# GPU config
  use_cuda: True
  device: "cuda"
  gpu: 0
  seed: 2021
  device_ids: [0]
  use_multi_gpu: False

