#!/bin/bash

# DMVAER model training script
python -u run.py --model 'DMVAER' \
                 --task 'short_term_forecasting' \
                 --data_name "MFP" \
                 --data_path 'C:\Study\Code\datasets\MFP\data\MFP_combined_data.csv' \
                 --target 'PT501' \
                 --data_aug False \
                 --use_amp False \
                 --num_workers 1 \
                 --if_missing False \
                 --missing_rate 0 \
                 --use_axliary_var False \
                 --enc_in 17 \
                 --dec_in 17 \
                 --C_in 17 \
                 --C_out 1 \
                 --seq_len 16 \
                 --embed 'TimeF' \
                 --freq 's' \
                 --factor 1 \
                 --label_len 16 \
                 --pred_len 6 \
                 --d_model 16 \
                 --d_ff 32 \
                 --z_global_dim 16 \
                 --z_local_dim 16 \
                 --z_dim 16 \
                 --n_heads 8 \
                 --e_layers 1 \
                 --d_layers 1 \
                 --dropout 0.05 \
                 --activation 'GELU' \
                 --n_components 3 \
                 --batch_size 64 \
                 --learning_rate 0.001 \
                 --epoch 300 \
                 --if_valid True \
                 --patience 10 \
                 --lradj 'cosine' \
                 --inverse True \
                 --use_cuda True \
                 --device "cuda" \
                 --gpu 0 \
                 --seed 2021 \
                 --device_ids "[0]" \
                 --use_multi_gpu False
