#!/bin/bash

# iTransformer model training script
python -u run.py --model 'iTransformer' \
                 --task 'short_term_forecasting' \
                 --data_name "MFP" \
                 --data_path 'C:/Study/Code/datasets/MFP/data/MFP_combined_data.csv' \
                 --target 'PT501' \
                 --if_scale True \
                 --data_aug False \
                 --use_amp False \
                 --num_workers 1 \
                 --if_missing False \
                 --missing_rate 0 \
                 --use_axliary_var False \
                 --enc_in 17 \
                 --dec_in 17 \
                 --C_in 17 \
                 --C_out 1 \
                 --seq_len 16 \
                 --embed 'TimeF' \
                 --freq 's' \
                 --factor 1 \
                 --label_len 10 \
                 --pred_len 6 \
                 --n_components 5 \
                 --d_model 64 \
                 --n_heads 8 \
                 --d_ff 1024 \
                 --e_layers 1 \
                 --d_layers 1 \
                 --dropout 0.05 \
                 --activation 'gelu' \
                 --batch_size 64 \
                 --learning_rate 0.001 \
                 --epoch 200 \
                 --if_adj_lr True \
                 --if_valid False \
                 --patience 10 \
                 --lradj 'cosine' \
                 --annealing_steps 20 \
                 --inverse False \
                 --use_cuda False \
                 --device "cuda" \
                 --gpu 0 \
                 --seed 2021 \
                 --device_ids "[0]" \
                 --use_multi_gpu False