# configs.yaml

params:
# Data Config
  model: 'DMVAER'
  task: 'short_term_forecasting' # type: str, default: short_term_forecasting, help: ['short_term_forecasting', 'soft_sensor']
  data_name: "PPGAS" # type: str, default: None, help: ['MFP', 'DEB', 'SRU','PPGAS','PTA']
  data_path: './data/PPGAS/gt_2011.csv' # type: str, default: None, help: Path to the dataset
  target: 'NOX' # type: str, default: None, help: Target variable name
  data_aug: False # type: bool, default: False, help: If use data augmentation for Deb and SRU dataset Augmentation Options #
  use_amp: False # type: bool, default: False, help: If use automatic mixed precision training
  num_workers: 1 # type: int, DataLoader the number of workers
  if_missing: False # type: bool, default: False, help: If exists Missing Data
  missing_rate: 0 # type: float, default: 0, help: Missing data rate [0:0.5]
   # type: bool, default: False, help: If use mode variable for multi_mode dataset

# Model Config
  enc_in: 10  # type: int, default: 17
  dec_in: 10  # Dimension of decoder Input
  C_in: 10  # Dimension of Channel Input
  C_out: 1  # Dimension of Channel Output
  seq_len: 16 #
  embed: 'TimeF'
  freq: 's'
  factor: 1
  label_len: 16
  pred_len: 6     # type: int, default: 6, help: Prediction Length,re
  d_model: 32
  d_ff: 64        # type: int, fast-forward network dimension
  z_global_dim: 16
  z_local_dim: 16
  z_dim: 16       # type: int, Embedding dimension of X
  n_heads: 8 
  e_layers: 1
  d_layers: 1
  dropout: 0.05
  activation: 'GELU'
  n_components: 3


# Train Config
  batch_size: 64 #128
  learning_rate: 0.001 # 0.0005
  epoch: 100
  
  patience: 10 # 25
  lradj: 'cosine' # learning rate adjustment strategy: [type1, type2, cosine]


# Test Config
  inverse: True # If the data is scaled, inverse the data to the original scale

# GPU config
  use_cuda: True
  device: "cuda"
  gpu: 0
  seed: 2021
  device_ids: [0]
  use_multi_gpu: False

