
                        python -u run.py \
                        --model 'DMVAER' \
                        --task 'soft_sensor' \
                        --data_name "DC" \
                        --data_path './data/DC/debutanizer_column.csv' \
                        --data_aug \
                        --target 'y_1' \
                        --num_workers 1 \
                        --missing_rate 0 \
                        --C_in 13 \
                        --enc_in 13 \
                        --C_out 1 \
                        --seq_len 16 \
                        --label_len 16 \
                        --pred_len 6 \
                        --d_model 512 \
                        --n_components 3 \
                        --z_global_dim 32 \
                        --z_local_dim 32 \
                        --batch_size 64 \
                        --DMVAER_loss_weight 0.1 1 1 1 0.01 \
                        --learning_rate 0.001 \
                        --epoch 300 \
                        --patience 10 \
                        --lradj 'cosine' \
                        --inverse \
                        --use_cuda  \
                        --device "cuda" \
                        --gpu 0 \
                        --seed 2021 \
